calc_mean.o: calc_mean.c
gcc -g -c calc_mean.c -o calc_mean.o


calc_sum.o: calc_sum.c
gcc -g -c calc_sum.c -o calc_sum.o

#ar rcs libmymath.a calc_sum.o calc_mean.o 
#gcc -static -g main.c -L. -lmymath -o statically_linked
